name: 90 Days Activity Generator

on:
  workflow_dispatch:

permissions:
  contents: write   # 🔥 MUHIM (push uchun)

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  backdate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate commits
        run: |
          git config user.name "zarnigor"
          git config user.email "zarnigorkamilova85@gmail.com"

          for i in {90..1}
          do
            DAY=$(date -d "$i days ago" +%u)
            RAND=$((RANDOM % 100))

            # Ish kunlari ko‘proq commit
            if [ $DAY -lt 6 ]; then LIMIT=40; else LIMIT=85; fi

            if [ $RAND -gt $LIMIT ]; then
              COUNT=$((1 + RANDOM % 8))

              for j in $(seq 1 $COUNT)
              do
                DATE=$(date -d "$i days ago" +"%Y-%m-%dT%H:%M:%S")

                echo "activity $RANDOM" > file.txt
                git add file.txt

                GIT_AUTHOR_DATE="$DATE" \
                GIT_COMMITTER_DATE="$DATE" \
                git commit -m "activity update"
              done
            fi
          done

      - name: Push
        run: git push origin HEAD:main
